### ISSUE TITLE
The verion 2.0 (extended-csv-dataset-config-2.0) does not work with JMeter 5.5 or 5.6.2

### ISSUE THREAD

**Issue by vin4winning** [rollno748/Extended-csv-dataset-config#15]
Hello @rollno748 - The JMeter script which has the extended csv data set to any request in the script, does not open in JMeter and shows a dialog to install the plug-in first. Up on installing the plug-in "extended-csv-dataset-config-2.0" and restarting JMeter, it still does not open the script and shows the same message to install the plugin. 

I am assuming JMeter is not detecting the installed plug-in "extended-csv-dataset-config-2.0" (still shows in available plug-ins tab of plug-in manager after installation too).

**Note**: I removed the jar file 2.0 from ext folder of lib directory and replaced with version 1.1 (di-extended-csv-1.1.jar) and it works fine.
So the problem is with version 2.0

**Comment by rollno748** [comment]
Hi 
Thanks for reporting this issue - Can you please provide a sample jmeter.log /jmx file to investigate furuther

**Comment by rollno748** [comment]
Hi,

I did a quick try on JMeter-5.5 where i don't see any issue with it

![image](https://github.com/rollno748/Extended-csv-dataset-config/assets/18440913/dc28842c-fd8b-45d2-ac8f-e62f632337ec)

JMeter-5.6.2

![image](https://github.com/rollno748/Extended-csv-dataset-config/assets/18440913/828ffb7a-3147-4337-bd5f-68e344bf5b92)

I dont see any issues with it - Can you please share your jmeter.log file ?

**Comment by rollno748** [comment]
If you could share the jmeter.log - that would be of great help to suggest you some information

**Comment by vin4winning** [comment]
[jmeter.log](https://github.com/rollno748/Extended-csv-dataset-config/files/12465555/jmeter.log)
Here it is and I do not see anything fishy here either!

**Comment by rollno748** [comment]
You have jar conflicts - that might cause this kind of weird behaviour with JMeter 
You should fix that first 

Try removing the below plugins/lib and give it a try

jmeter-bzm-correlation-recorder-2.1.jar
jmeter-bzm-correlation-recorder-2.0.3.jar

json-20190722.jar

**Comment by vin4winning** [comment]
Sure, thanks! I removed the log file now.

**Comment by vin4winning** [comment]
The version 1.1 of the extended csv dataset config works fine though! very strange.

**Comment by rollno748** [comment]
Did removing the above conflicts, fixed the issue ?

**Comment by vin4winning** [comment]
I haven't tried yet. Will do later today or tomorrow and get back. Thanks though for suggesting :)

**Comment by rollno748** [comment]
Any updates ?

**Comment by vin4winning** [comment]
Hi, I tried now and it still did not work after resolving the conflicts. Here is the exception I see:

CannotResolveClassException: com.di.jmeter.config.ExtendedCsvDataSet

 Detail:com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:66)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/hashTree[6]/hashTree/com.di.jmeter.config.ExtendedCsvDataSet
line number         : 3455
version             : 5.5
-------------------------------

**Comment by vin4winning** [comment]
Hi! I just have put both 1.1 and 2.0 versions of Jar file in ../lib/ext and I am able to open the script now.
Anyways, sounds like this is only an issue on my machine, so fine to close the issue.

**Comment by vin4winning** [comment]
Also, thank you for this plug-in. This is great!

**Comment by rollno748** [comment]
Thanks - keep supporting 👍 
Please hit a star, if you like it !
