### ISSUE TITLE
Select Row Random with Quoted Data is sequential

### ISSUE THREAD

**Issue by prashker** [rollno748/Extended-csv-dataset-config#3]
https://github.com/rollno748/Extended-csv-dataset-config/blob/2a0756c87fb435fd33907d214322a4b281a07f60/src/main/java/com/di/jmeter/config/ExtendedCsvDataSet.java#L113

Most likely issue with this line

If I turn off quoted data, lines are random again

**Comment by rollno748** [comment]
Hello Thanks for bringing this up.
We are well aware of the issue with qouted data. We are about to release the next version that will cover the UI and quoted data issue

**Comment by rollno748** [comment]
This issue is fixed in version 2.0 (which will be released soon)
